export const CHATS_ADD_USER_REQUEST = "CHATS_ADD_USER_REQUEST";
export const CHATS_ADD_USER_SUCCESS = "CHATS_ADD_USER_SUCCESS";
export const CHATS_ADD_USER_FAIL = "CHATS_ADD_USER_FAIL";

export const CHATS_CREATE_GROUP_REQUEST = "CHATS_CREATE_GROUP_REQUEST";
export const CHATS_CREATE_GROUP_SUCCESS = "CHATS_CREATE_GROUP_SUCCESS";
export const CHATS_CREATE_GROUP_FAIL = "CHATS_CREATE_GROUP_FAIL";

export const CHATS_GET_ALL_CHATS_REQUEST = "CHATS_GET_ALL_CHATS_REQUEST";
export const CHATS_GET_ALL_CHATS_SUCCESS = "CHATS_GET_ALL_CHATS_SUCCESS";
export const CHATS_GET_ALL_CHATS_FAIL = "CHATS_GET_ALL_CHATS_FAIL";

export const CHATS_GET_CHAT_BY_ID_REQUEST = "CHATS_GET_CHAT_BY_ID_REQUEST";
export const CHATS_GET_CHAT_BY_ID_SUCCESS = "CHATS_GET_CHAT_BY_ID_SUCCESS";
export const CHATS_GET_CHAT_BY_ID_FAIL = "CHATS_GET_CHAT_BY_ID_FAIL";

export const CHATS_GET_CHAT_BY_USER_REQUEST = "CHATS_GET_CHAT_BY_USER_REQUEST";
export const CHATS_GET_CHAT_BY_USER_SUCCESS =
    "CHATS_GET_CHAT_BY_USER_SUCCESS";
export const CHATS_GET_CHAT_BY_USER_FAIL = "CHATS_GET_CHAT_BY_USER_FAIL";

export const CHATS_REMOVE_USER_REQUEST = "CHATS_REMOVE_USER_REQUEST";
export const CHATS_REMOVE_USER_SUCCESS = "CHATS_REMOVE_USER_SUCCESS";
export const CHATS_REMOVE_USER_FAIL = "CHATS_REMOVE_USER_FAIL";

export const CHATS_RENAME_CHAT_REQUEST = "CHATS_RENAME_CHAT_REQUEST";
export const CHATS_RENAME_CHAT_SUCCESS = "CHATS_RENAME_CHAT_SUCCESS";
export const CHATS_RENAME_CHAT_FAIL = "CHATS_RENAME_CHAT_FAIL";

export const CHATS_REFRESH_CHATS = "CHATS_REFRESH_CHATS";
export const CHATS_REFRESH_NEW_MESSAGE = 'CHATS_REFRESH_NEW_MESSAGE'
