export const CHAT_REQUEST = 'CHAT_REQUEST'
export const CHAT_REQUEST_SUCCESS = 'CHAT_REQUEST_SUCCESS'
export const CHAT_REQUEST_FAIL = 'CHAT_REQUEST_FAIL'

export const NEW_CHAT_REQUEST = 'NEW_CHAT_REQUEST'
export const NEW_CHAT_REQUEST_SUCCESS = 'NEW_CHAT_REQUEST_SUCCESS'
export const NEW_CHAT_REQUEST_FAIL = 'NEW_CHAT_REQUEST_FAIL'
