export const ADD_USER_REQUEST = "ADD_USER_REQUEST";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_FAIL = "ADD_USER_FAIL";

export const CREATE_GROUP_REQUEST = "CREATE_GROUP_REQUEST";
export const CREATE_GROUP_SUCCESS = "CREATE_GROUP_SUCCESS";
export const CREATE_GROUP_FAIL = "CREATE_GROUP_FAIL";

export const GET_ALL_CHATS_REQUEST = "GET_ALL_CHATS_REQUEST";
export const GET_ALL_CHATS_SUCCESS = "GET_ALL_CHATS_SUCCESS";
export const GET_ALL_CHATS_FAIL = "GET_ALL_CHATS_FAIL";

export const GET_CHAT_BY_ID_REQUEST = "GET_CHAT_BY_ID_REQUEST";
export const GET_CHAT_BY_ID_SUCCESS = "GET_CHAT_BY_ID_SUCCESS";
export const GET_CHAT_BY_ID_FAIL = "GET_CHAT_BY_ID_FAIL";

export const GET_CHAT_BY_USER_REQUEST = "GET_CHAT_BY_USER_REQUEST";
export const GET_CHAT_BY_USER_SUCCESS =
    "GET_CHAT_BY_USER_SUCCESS";
export const GET_CHAT_BY_USER_FAIL = "GET_CHAT_BY_USER_FAIL";

export const REMOVE_USER_REQUEST = "REMOVE_USER_REQUEST";
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";
export const REMOVE_USER_FAIL = "REMOVE_USER_FAIL";

export const RENAME_CHAT_REQUEST = "RENAME_CHAT_REQUEST";
export const RENAME_CHAT_SUCCESS = "RENAME_CHAT_SUCCESS";
export const RENAME_CHAT_FAIL = "RENAME_CHAT_FAIL";
