export const SEARCH_SEARCH_USERS_REQUEST = "SEARCH_SEARCH_USERS_REQUEST";
export const SEARCH_SEARCH_USERS_SUCCESS = "SEARCH_SEARCH_USERS_SUCCESS";
export const SEARCH_SEARCH_USERS_FAIL = "SEARCH_SEARCH_USERS_FAIL";
