export const INIT_CONNECTION = "INIT_CONNECTION";
export const SOCKET_SET_IS_CONNECTED = "SOCKET_SET_IS_CONNECTED";
export const SOCKET_EMIT_NEW_MESSAGE = "SOCKET_EMIT_NEW_MESSAGE";
export const SOCKET_ADD_LISTENER = "SOCKET_ADD_LISTENER";
export const SOCKET_REMOVE_LISTENER = "SOCKET_REMOVE_LISTENER";
export const SOCKET_EMIT_EVENT = "SOCKET_EMIT_EVENT";
